### PR TITLE
Updated packages to their latest

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by kurisubrooks** [comment]
Tested with new dependency versions, still works :+1:

**Comment by mikaelbr** [comment]
Hi! Thanks for your contribution! I think all the major updates are good. However, I don't see why the minor ranges should be bumped. This causes less packages to be deduped by npm as it's more restrictive. As a rule of thumb, I try to have the version ranges as forgiving as possible, allowing for more deduping.

**Comment by kurisubrooks** [comment]
Sorry for misunderstanding here, but might I ask what you mean by "deduping"? @mikaelbr

**Comment by lipis** [comment]
@mikaelbr The you can only use the major version if you like `^2` if you don't want to bump the minor ones..

**Comment by mikaelbr** [comment]
"deduping" is a term for de-duplication, or reducing the number of duplicate packages in the dependency tree. So say we have two packages: package A and B.

A is dependent on module "C" on version `^1.0.0` and B is dependent on `^1.1.0`. This means, if you have installed C version e.g. `1.0.5` A and B cannot share C, but if B has a lower version range they can share C and we only need one instance of C, not two. Probably a poor explanation, but hope it makes sense. I can try to elaborate later when I have more time if there are any more questions.

**Comment by kurisubrooks** [comment]
I'm unsure if this is related or not, but I run node-notifier just fine on the latest dependent packages. No build errors or anything either. 
Just thought i'd let you know ~

**Comment by mikaelbr** [comment]
Yeah, node-notifier will probably run just fine, but the problem is if we have too small window of dependency versions, we will possibly cause our consumers to have some duplicate packages. Also, there is rarely any need to bump major release, unless a major release introduces a feature we want to use / are dependent on.

**Comment by lipis** [comment]
I think we can close that one..

**Pull request closed without merging**
