### PR TITLE
remove the AppID if not exist, fix the notification for windows 8.1

### PR DESCRIPTION
**Pull request by teliz**
hello, I needed to make these changes to work on windows 8.1, it make any sense ?

### CODE REVIEW

**Comment by rafaelcardoso** [comment]
hey @teliz.
I ran into the same issue.

what is happening is that the prop `appID` is being passed as a empty string `' '``to the `SnoreToast.exe``. I think this prop should be optional

**Comment by ericman314** [comment]
+1

I am using version 5.1.2 on Windows 8.1. I was trying to set my own `appID` (I install my app using electron builder, setting the appId in the build settings to the same value), but it was being replaced with an empty string.

After seeing [this](https://github.com/mikaelbr/node-notifier/blob/6da61deaf0d36df2b1a61527309c7ad8bef58582/lib/utils.js#L359-L364) I realized one workaround would be to set `appName` instead of `appID`. This works. But it did cause very much frustration for several hours.

**Comment by mikaelbr** [comment]
This is a tricky one, I tink. It needs to be thoroughly tested on Windows (also for first time use/clean environment), but for the moment I don't have easy access to Windows, so that is why I've delayed this, I'm sorry to say. But if anyone could test it for different use cases I'll be happy to merge a fix.

**Comment by mikaelbr** [comment]
Thanks for this. Seems having default empty appId has caused some ruckus. It's been fixed in master branch by not having else branch.

**Pull request closed without merging**
