### PR TITLE
Update to terminal-notifier 1.6.2

### LINKED ISSUE #18: Notification icon has black border
On OS X (10.9.4) I'm seeing a black border around any `appIcon` or `contentImage` I pass into the notification. Additionally, the original Terminal icon still shows up (smaller) next to the title.  Is there any way to only show my app's icon, without a border?

### PR DESCRIPTION
**Pull request by pdud**
Great module! I'm using it on https://github.com/pdud/ember-cli-build-notifications.

This pull request removes the black border on OS X around image which fixes #18.

Here is what it looks like with this update.

agent

And here is the difference on  ember-cli-build-notifications

example

### CODE REVIEW

**Comment by mikaelbr** [comment]
Great, @pdud ! Thanks for your work!

**Comment by pdud** [comment]
Any idea when we can expect a new node-notifier npm version? :grin:

**Comment by mikaelbr** [comment]
I believe about now! :cake: 

```
➜  node-notifier git:(master) npm publish
+ node-notifier@4.1.1
```

**Comment by pdud** [comment]
:yum:

Thank you! and thanks again for the great module!

**Pull request merged**
