### PR TITLE
Notifu now more explicit about its 3-clause BSD license

### PR DESCRIPTION
**Pull request by ixe013**
There used by be an unclear mention of Notifu's 3-clause BSD license in the application properties dialog. Made it explicit in every souce file, and at run-time with the `/l` option:

image

### CODE REVIEW

**Comment by jnielson94** [comment]
Thanks for the PR! I'm not super familiar with how we're using notifu yet, but I noticed that there's two versions in the vendor folder - could you update both to ensure they stay in sync? :) @mikaelbr might know more of what we need to do to test this (or if we can).

**Comment by ixe013** [comment]
Thanks for pointing it out @jnielson94, I only searched for occurences of `notifu.exe`!

I don't know how to test Notifu inside node-notifier... The interface is the same, with the addition of the `/l` switch that displays the license (no use for your project).

**Comment by jnielson94** [comment]
So far as I've found in brief searching we use it for the native piece behind the WindowsBalloon notifications, which I think you can try to use directly to test? Looking at [the flow chart](https://github.com/mikaelbr/node-notifier/blob/master/DECISION_FLOW.md) it looks like it only gets pulled in on windows <8 (so windows 7?) Since the SnoreToast library for the toaster notifications isn't compatible with those versions? That's all I've come up with so far though.

**Comment by mikaelbr** [comment]
That's correct, @jnielson94. It's used as a fallback for Windows versions not supporting toasts (e.g. Windows 7). You could also use it directly:

```js
const WindowsBalloon = require('node-notifier/notifiers/balloon');
new WindowsBalloon().notify({ message: 'Testing' });
```

**Comment by jnielson94** [comment]
I'm gonna go ahead and merge this. I tested it locally (and believe @ixe013) and it looks to work fine. I'll add a note to the README about the copyright on notifu in a different commit along with an example that utilizes it directly for future testing :)

**Pull request merged**
