### PR TITLE
Fix customPath option in WindowsToaster constructor

### PR DESCRIPTION
**Pull request by yoavain**
Fix https://github.com/mikaelbr/node-notifier/issues/377 

This PR https://github.com/mikaelbr/node-notifier/pull/373 caused customPath set in WindowsToaster constructor to be ignored.

The fix is a one-liner, but I also added a test that test the entire flow using nexe

### CODE REVIEW

**Comment by yoavain** [comment]
My fix assumes that customPath sent in message can override the one set in the constructor

**Comment by yoavain** [comment]
Any update on this one?

**Comment by Araxeus** [comment]
image
You commited package.lock

also the only change in the whole PR should just be
```js
    const localNotifier = options.customPath || this.options.customPath
      (notifier + '-x' + (is64Bit ? '64' : '86') + '.exe');
```
and if you want open others pull request for other changes

**Comment by yoavain** [comment]
I committed package-lock.json because
1. the committed one, is out of sync from package.json file
2. I added some dev dependencies for tests.

I can leave this PR as is, and open another one, just with the one-liner fix

**Comment by Araxeus** [comment]
> I can leave this PR as is, and open another one, just with the one-liner fix

Sounds good to me, that one should hopefully gets merged more quickly 😅

**Comment by yoavain** [comment]
Opened this PR:
https://github.com/mikaelbr/node-notifier/pull/392

**Pull request merged**
