### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to the `README.md` file to display the npm install size

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi. Thanks for the PR. I'm not entirely sure why this is needed though, to be honest. What is the end goal of showing the download size?

I get this can add value for dependencies intended for frontend bundles (as a part of making decisions of "ROI" for a dependency), but this is intended a whole other use case. 1 MB isn't that much for a tool of this nature in my opinion, and I feel this can just lead to bikeshedding. What do you think?

**Comment by styfle** [comment]
Correct, 1 MB is not that much for this type of tool.
Data doesn't have to be good or bad, it's just information that users can use to make a decision: should I use this package?

You can read more about why Package Phobia exists: https://github.com/styfle/packagephobia#readme

**Comment by styfle** [comment]
It looks like tests failed but I don't see any test for the README.
Any idea why this is failing?

**Comment by egoist** [comment]
And now it grows to 5MB 😅

image

**Review by dustpan28645 — APPROVED** [review]

**Comment by mikaelbr** [comment]
There was someone attacking the repo with comments and approval/rejection reviews triggering this one again, but as you've taken the time to update the PR and fix merge conflicts I can merge this if you feel it is helpful. Currently, it has a lot of potential optional deps without being lazy-loaded (64bit vs 32bit, OS specific etc) which can be approved and reduce the install size dramatically, so this can be approved and visualized by the badge.

**Pull request merged**
