### PR TITLE
Fix hang on Disabled Windows 10 Notifications

### LINKED ISSUE #334: Hang on Disabled Windows Notifications
## Expected Behavior

Disabling Windows 10 notifications should not hang `node-notifier`.

## Actual Behavior

Running `node-notifier` on Windows 10 clients with notifications results in a hang.

## Repro

The simplest repro is to disable Windows 10 notifications as shown below and run `npm run example` in the repo.

I'm trying a scenario like:

```js
try {
  const notifier = require('node-notifier');
  notifier.notify({
    title: 'Title',
    message: 'message',
    wait: true
  });
} catch {
  // Notifications may be disabled in OS, causing an error.
  // node-notifier may not installed.
  // Silently fail.
}
```

I'd just simply like to catch exceptions and silently continue.

However, if notifications are disabled on Windows 10:

image

This example will hang forever on the command line:

```
λ node not.js
Notifications are disabled
Reason: DisabledForUser Please make sure that the app id is set correctly.
Command Line: G:\git\ooui-dp\node_modules\node-notifier\vendor\snoreToast\snoretoast-x64.exe -pipeName \\.\pipe\notifierPipe-f80dfe8f-ff7d-42ce-becd-0a2e340a9d59 -m message -t Title
```

I tried searching the docs and existing issues for a way to "detect" whether notifications are disabled, but I haven't found anything. I'd also like to suppress error output like this if possible. In any case, it doesn't seem like the call to `node-notifier` should hang like this.

## Tools
node-notifier: 7.0.1
node: 12.18.0
OS: Windows 10 Pro 1909

### PR DESCRIPTION
**Pull request by JasonGore**
Fix named pipe server hang when notifications are disabled in Windows 10.

This PR can't address root cause (due to snoretoast's behavior) but at least resolves the hanging issue. I think it's important to fix with some kind of change at least temporarily to prevent a permanent hang in certain use cases. (More info in #334.)

Fixes #334.

### CODE REVIEW

**Comment by JasonGore** [comment]
The prettier pre-commit hook lint rules are at odds with the `npm run lint` configuration.

**Comment by JasonGore** [comment]
I had to use `git commit --no-verify` to fix the lint issues.

**Comment by JasonGore** [comment]
@mikaelbr Do you think there's any chance this fix will get merged? I want to deploy `node-notifier` but I can't since it will hang for some of our users. Thanks!

**Comment by mikaelbr** [comment]
Thanks for this! Merging now

**Comment by JasonGore** [comment]
@mikaelbr Thanks for merging! Do you know when the next release will occur?

**Comment by mikaelbr** [comment]
Right about now!

```
+ node-notifier@7.0.2
```

Get it while it's fresh! 🍣

**Pull request merged**
