### PR TITLE
node-notifier v6 release

### PR DESCRIPTION
**Pull request by mikaelbr**
Re-added this as a seperate work branch for the entire release, with the new timeout semantics, and updated dependencies.

Did this as a branch as there were some issues with previous releases, and having the master branch without the breaking changes for now is easier than to jump between versions and tags.

Should be merged when we have the scope of v6 right and all breaking changes are ready.

## Scope

- [x] Upgrade snoreToast 6.0.0
- [x] Fix deactivating timeout on Notification center
- [x] Test snoreToast upgrades on Windows

### CODE REVIEW

**Comment by mikaelbr** [comment]
@jnielson94 Can you think of other major changes we should include in the scope for this release?

**Comment by jnielson94** [comment]
So far as I'm aware the things to include are:
- Dropping node v6 support
- Upgrading to latest snoretoast (and related api changes)
- Default timeout that you can overwrite

I think you've captured those in your description?

**Comment by weilinzung** [comment]
more updates?

**Comment by mikaelbr** [comment]
We are awaiting testing new snoreToast on Windows. @jnielson94 is currently out traveling and doesn't have access to test (nor have I right now).

**Comment by weilinzung** [comment]
more updates?

**Comment by mikaelbr** [comment]
@jnielson94 :dizzy_face: Didn't catch that you had tested this out. Sorry about that! The docs look good. I'm merging this and publishing v6 right away.

**Comment by mikaelbr** [comment]
Released now! Thanks for all your work, @jnielson94 .

```
+ node-notifier@6.0.0
```

**Pull request merged**
