### PR TITLE
Automagically Bind `notify` Methods

### PR DESCRIPTION
**Pull request by Daniihh**
Automagically bind `notify` methods on all wrapper classes so the notify method can be destructured within the import statement and not run into any `this` related errors.

### CODE REVIEW

**Comment by mikaelbr** [comment]
Thanks!

**Comment by yvele** [comment]
Why is this breaking? 🤔

**Comment by mikaelbr** [comment]
Strictly not very breaking. The most notable breaking I found was sanitizing timeout on snoretoast handling (see changelog https://github.com/mikaelbr/node-notifier/blob/master/CHANGELOG.md#breaking-changes). But I also marked this as breaking in the changelog as it, in theory, does break from existing API.

**Comment by yvele** [comment]
Thanks

**Pull request merged**
