### PR TITLE
Fixed a bug that did not work on windows8.1.

### PR DESCRIPTION
**Pull request by vomvoru**
https://github.com/KDE/snoretoast#snoretoast

If your application already has a shortcut in the startmenu, which provides an appID please pass this appID, an appID is needed and is also used to determine the application icon displayed in the toast notification.

SnoreToast.exe -m "msg" -t "title" -appID " "     -->  fail
SnoreToast.exe -m "msg" -t "title" -appID ""      -->  success
SnoreToast.exe -m "msg" -t "title"                      -->  success  --> best!

:)

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi. The concept for passing an empty appId is to avoid the SnoreToast sub-title being added. As it is now, the first notification will error if not passing, but this is also true if you pass a valid appId I found. The notification will work, but return an error.

Maybe we need to do some more research for what consequences the appId has, but I suspect that the fail/success case in your case is as the notifications has been triggered beforehand and thus the notification item is added in the notification options in the Windows Control Panel.

**Comment by vomvoru** [comment]
Okay. I will debug and try to find a solution.
This is difficult for me.. OTL

**Comment by DiamondeX** [comment]
My results:
(1) SnoreToast.exe -m "msg" -t "title" -appID " " --> fail always
(2) SnoreToast.exe -m "msg" -t "title" --> fail first time with message `Installing shortcut: ...`, success later
(3) SnoreToast.exe -m "msg" -t "title" -appID "" --> fail without (2), success after (2)

**Comment by mikaelbr** [comment]
I think this is due to some register app in notification issue causing it some times to fail initially and other times to work. Need to investigate what the root cause is, but it seems to work on fresh windows installations – so maybe try to remove node-notifier, snoretoast etc from the notification list in the Control Panel.

**Pull request closed without merging**
