### PR TITLE
Upgrade terminal-notifier to version 1.6.3.

### PR DESCRIPTION
**Pull request by kid-icarus**

### CODE REVIEW

**Comment by kurisubrooks** [comment]
We use a custom build of terminal-notifier that supports `wait`, did you build Terminal Notifier from our repositories or the base repo?

**Comment by mikaelbr** [comment]
What, @kurisubrooks says. See https://github.com/mikaelbr/terminal-notifier

**Comment by kurisubrooks** [comment]
@mikaelbr maybe update your custom repo with the latest version from the master repo, update node-notifier and we can close this?

**Comment by mikaelbr** [comment]
Yep, @kurisubrooks. Will see if I can fit it in to the schedule. 👍

**Comment by kurisubrooks** [comment]
👏

**Comment by mikaelbr** [comment]
Updated in f2a8ad51da8a66b34208df7726cf587cb96982f6. Thanks for reminding us.

**Comment by kid-icarus** [comment]
Thanks folks 💯

**Pull request closed without merging**
